imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration for testing.
# Uses a sqlite database for testing, located in var/ folder.
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.root_dir%/../var/fenrir_test.sqlite"
        host:     127.0.0.1
        port:     ~
        dbname:   fenrir_test
        charset:  UTF8
